import { TamaguiProvider } from "tamagui";
import config from "./src/tokens/tamagui.config";

// Storybook UI is auto-generated by @storybook/react-native
// eslint-disable-next-line @typescript-eslint/no-var-requires
const StorybookUI = require("./.ondevice").default;

export default function App() {
  return (
    <TamaguiProvider config={config}>
      <StorybookUI />
    </TamaguiProvider>
  );
}
