import { useFonts } from "expo-font";
import { TamaguiProvider } from "tamagui";
import config from "./src/tokens/tamagui.config";

// Storybook UI is auto-generated by @storybook/react-native

const StorybookUI = require("./.ondevice").default;

export default function App() {
  const [fontsLoaded] = useFonts({
    "Pretendard-Regular": require("./assets/fonts/Pretendard-Regular.otf"),
    "Pretendard-Medium": require("./assets/fonts/Pretendard-Medium.otf"),
    "Pretendard-SemiBold": require("./assets/fonts/Pretendard-SemiBold.otf"),
    "Pretendard-Bold": require("./assets/fonts/Pretendard-Bold.otf"),
  });

  if (!fontsLoaded) return null;

  return (
    <TamaguiProvider config={config}>
      <StorybookUI />
    </TamaguiProvider>
  );
}
